# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='tags',
            field=models.ManyToManyField(to='ideas.Tag'),
        ),
    ]
