# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-20 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_auto_20160620_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
