# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0009_auto_20160725_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default='this is a comment'),
        ),
    ]
