# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-08 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0010_auto_20160808_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(),
        ),
    ]
