# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-15 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0011_auto_20160808_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
